name: WacosBans
main: ca.wacos.wacosbans.WacosBans
version: 1.0
authors: [Jarcode]
website: "wacos.ca"
load: STARTUP
commands:
  ban:
     description: Ban a player
     permission: wacosbans.ban
  banip:
     description: Disabled command
     aliases: [unbanip, pardonip]
     permission: wacosbans.disabled
  tempban:
     description: Temporarily ban a player
     permission: wacosbans.tempban
  warn:
     description: Warn a player
     permission: wacosbans.warn
  pardon:
     description: Pardon a player
     aliases: [unban]
     permission: wacosbans.pardon
  dump:
     description: Dumps a player's ban/tempban/warning history
     aliases: [history]
     permission: wacosbans.dump
permissions:
   wacosbans.*:
     description: Gives access to all WacosBans commands
     children:
       wacosbans.ban: true
       wacosbans.tempban: true
       wacosbans.disabled: true
       wacosbans.warn: true
       wacosbans.pardon: true
       wacosbans.dump: true